# Artificial Neural Network

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

2022-06-14 20:45:19.014574: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2022-06-14 20:45:20.591486: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-14 20:45:20.591520: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [6]:
tf.__version__

'2.9.1'

## Part 1 - Data Preprocessing

### Importing the dataset

In [7]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [8]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [9]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])

In [11]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [12]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [13]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 0, test_size=0.2)

### Feature Scaling

In [15]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [16]:
print(X_train)

[[-1.01460667 -0.5698444   1.74309049 ...  0.64259497 -1.03227043
   1.10643166]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
  -0.74866447]
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.48533467]
 ...
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.41231994]
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497  0.9687384
   0.84432121]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497 -1.03227043
   0.32472465]]


## Part 2 - Building the ANN

### Initializing the ANN

In [17]:
ann = tf.keras.models.Sequential()

2022-06-14 20:46:00.211858: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-06-14 20:46:00.211887: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-06-14 20:46:00.211924: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (fedora): /proc/driver/nvidia/version does not exist
2022-06-14 20:46:00.212102: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


### Adding the input layer and the first hidden layer

In [18]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [19]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [20]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [21]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [22]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 900us/step - loss: 0.6858 - accuracy: 0.6270
Epoch 2/100
250/250 [==============================] - 0s 858us/step - loss: 0.4922 - accuracy: 0.8006
Epoch 3/100
250/250 [==============================] - 0s 923us/step - loss: 0.4578 - accuracy: 0.8069
Epoch 4/100
250/250 [==============================] - 0s 849us/step - loss: 0.4430 - accuracy: 0.8114
Epoch 5/100
250/250 [==============================] - 0s 813us/step - loss: 0.4309 - accuracy: 0.8174
Epoch 6/100
250/250 [==============================] - 0s 856us/step - loss: 0.4177 - accuracy: 0.8253
Epoch 7/100
250/250 [==============================] - 0s 786us/step - loss: 0.4018 - accuracy: 0.8344
Epoch 8/100
250/250 [==============================] - 0s 798us/step - loss: 0.3879 - accuracy: 0.8394
Epoch 9/100
250/250 [==============================] - 0s 821us/step - loss: 0.3792 - accuracy: 0.8416
Epoch 10/100
250/250 [==============================] - 0s 789us/step - l

250/250 [==============================] - 0s 945us/step - loss: 0.3420 - accuracy: 0.8589
Epoch 80/100
250/250 [==============================] - 0s 780us/step - loss: 0.3421 - accuracy: 0.8606
Epoch 81/100
250/250 [==============================] - 0s 802us/step - loss: 0.3417 - accuracy: 0.8591
Epoch 82/100
250/250 [==============================] - 0s 919us/step - loss: 0.3421 - accuracy: 0.8605
Epoch 83/100
250/250 [==============================] - 0s 797us/step - loss: 0.3414 - accuracy: 0.8618
Epoch 84/100
250/250 [==============================] - 0s 840us/step - loss: 0.3406 - accuracy: 0.8612
Epoch 85/100
250/250 [==============================] - 0s 851us/step - loss: 0.3411 - accuracy: 0.8600
Epoch 86/100
250/250 [==============================] - 0s 791us/step - loss: 0.3410 - accuracy: 0.8585
Epoch 87/100
250/250 [==============================] - 0s 853us/step - loss: 0.3411 - accuracy: 0.8599
Epoch 88/100
250/250 [==============================] - 0s 853us/step - loss:

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Solution**

In [23]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 0, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 [==============================] - 0s 69ms/step
[[False]]


### Predicting the Test set results

In [24]:
y_pred = ann.predict(X_test)
y_pred = y_pred>0.5
print(np.concatenate((y_pred.reshape(len(y_pred), 1),y_test.reshape(len(y_test), 1)),1))

63/63 [==============================] - 0s 651us/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [25]:
from sklearn.metrics import confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[1492  103]
 [ 176  229]]
0.8605
